services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=andrea'
    ports:
      - '27017:27017'
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - '9090:9090'
#    command:
#      - '--enable-feature=otlp-write-receiver'
#    volumes:
#      - ./src/main/resources/prometheus.yml:/prometheus/prometheus.yml
#  grafana:
#    image: grafana/grafana
#    ports:
#      - '3000:3000'
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - '5778:5778'
      - '16686:16686'
      - '4317'
      - '4318'
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: ["--config=/resources/collector-config.yml"]
    volumes:
#    add :Z if using SELinux to avoid permission errors: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
      - ./src/main/resources/:/resources/:Z
    ports:
      - '4317:4317'
      - '4318:4318'
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      CLUSTER_ID: QjvaUgwGQ0qSM66eyjDSZQ
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9094,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT